name: Check (Deno)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  deno-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Format check
        run: deno fmt --check
      - name: Lint
        run: deno lint
