name: Deploy (Deno Deploy)

on:
  push:
    branches: [ main ]

env:
  DENO_PROJECT: ${{ secrets.DENO_PROJECT }} # np. CH-Quantum-Dashboard
  ENTRYPOINT: server.js
  ROOT: .

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Deploy to Deno Deploy (Production)
        uses: denoland/deployctl@v1
        with:
          project: ${{ env.DENO_PROJECT }}
          entrypoint: ${{ env.ENTRYPOINT }}
          root: ${{ env.ROOT }}
          token: ${{ secrets.DENO_DEPLOY_TOKEN }}
